{% set name = "gradio" %}
{% set version = "3.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gradio-{{ version }}.tar.gz
  sha256: 1b0fc11e37974e693cb8e302ba429a8a188b8139d2dad96a58acceeebd5c70cb

build:
  number: 0
  noarch: python
  entry_points:
    - gradio=gradio.reload:run_in_reload_mode
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
    - hatch-requirements-txt
    - hatch-fancy-pypi-readme >=22.5.0
  run:
    - python >=3.7
    - aiofiles
    - aiohttp
    - altair >=4.2.0
    - fastapi
    - ffmpy
    - fsspec
    - httpx
    - huggingface_hub >=0.13.0
    - jinja2
    - markdown-it-py >=2.0.0
    - linkify-it-py
    - mdit-py-plugins <=0.3.3
    - markupsafe
    - matplotlib-base
    - numpy
    - orjson
    - pandas
    - pillow
    - pycryptodome
    - pydantic
    - pydub
    - python-multipart
    - pyyaml
    - requests
    - typing-extensions
    - uvicorn
    - websockets >=10.0

test:
  imports:
    - gradio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/gradio/
  summary: Python library for easily interacting with trained machine learning models
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Sclare87
