{% set name = "gradio" %}
{% set version = "4.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gradio-{{ version }}.tar.gz
  sha256: eae1058ffdd4adcfc25969a800903acbff4b58b50e7293de77d167560f06e356

build:
  number: 0
  noarch: python
  entry_points:
    - gradio=gradio.reload:run_in_reload_mode
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
    - hatch-requirements-txt
    - hatch-fancy-pypi-readme >=22.5.0
  run:
    - python >=3.8
    - aiofiles >=22.0,<24.0
    - altair >=4.2.0,<6.0
    - fastapi
    - ffmpy
    - gradio-client ==0.7.0
    - httpx
    - huggingface_hub >=0.14.0
    - importlib_resources >=1.3,<7.0
    - jinja2 <4.0
    - markupsafe ~=2.0
    - matplotlib-base ~=3.0
    - numpy ~=1.0
    - orjson ~=3.0
    - packaging
    - pandas >=1.0,<3.0
    - pillow >=8.0,<11.0
    - pydantic >=2.0
    - python-multipart
    - pydub
    - pyyaml >=5.0,<7.0
    - requests ~=2.0
    - semantic_version ~=2.0
    - tomlkit ==0.12.0
    - typing-extensions ~=4.0
    - typer[all] >=0.9,<1.0
    - uvicorn >=0.14.0

test:
  imports:
    - gradio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/gradio/
  summary: Python library for easily interacting with trained machine learning models
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Sclare87
