{% set name = "gradio" %}
{% set version = "3.24.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gradio-{{ version }}.tar.gz
  sha256: 19f11c8b5d9b23a22a7e0e3a32332146474d215588674afdfdbe2f86fe0a7811

build:
  number: 0
  noarch: python
  entry_points:
    - gradio=gradio.reload:run_in_reload_mode
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
    - hatch-requirements-txt
    - hatch-fancy-pypi-readme >=22.5.0
  run:
    - python >=3.7
    - aiofiles
    - aiohttp
    - altair >=4.2.0
    - fastapi
    - ffmpy
    - gradio_client>=0.0.5
    - httpx
    - huggingface_hub >=0.13.0
    - jinja2
    - markdown-it-py >=2.0.0
    - linkify-it-py
    - mdit-py-plugins <=0.3.3
    - markupsafe
    - matplotlib-base
    - numpy
    - orjson
    - pandas
    - pillow
    - pydantic
    - pydub
    - python-multipart
    - pyyaml
    - semantic_version
    - requests
    - typing-extensions
    - uvicorn
    - websockets >=10.0

test:
  imports:
    - gradio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/gradio/
  summary: Python library for easily interacting with trained machine learning models
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Sclare87
